name: Build

on:
  push:
    tags:
      - 'v0.*'
      - 'v1.*'
    branches:
      - 'master'
      - 'ci/*'
      - 'feat/*'
      - 'fix/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version-file: '.java-version'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-encryption-key: ${{ secrets.GradleEncryptionKey }} # openssl rand -base64 16
          validate-wrappers: true
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"
          gradle-version: wrapper
      - name: Run build
        run: ./gradlew build
      - name: Generate code coverage report
        run: ./gradlew koverXmlReport
      - name: Publish to GitHub Packages
        if: ${{ startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master' }}
        run: ./gradlew publishToGitHubPackages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: 'build/reports/kover/report.xml'
          token: ${{ secrets.CODECOV_TOKEN }}
